version: '3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    ports:
      - "8761:8761"

  configserver:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    ports:
      - "8888:8888"

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - configserver

  event-service:
    build:
      context: .
      dockerfile: ./event-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - configserver

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
