version: '3'
services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  configserver:
    image: config-server:latest
    build:
      context: ./config-server
    ports:
      - "8888:8888"

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
  
  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server

  event-service:
    image: event-service:latest
    build:
      context: ./event-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - config-server

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
