server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oussemajebali/microservicesproject.git
          search-paths: configurationFiles
          clone-on-start: true
